CREATE USER Pembelian IDENTIFIED BY asdf1234;
GRANT CREATE SESSION TO Pembelian;
GRANT
  SELECT,
  INSERT,
  UPDATE,
  DELETE
ON
  Pembelian
TO
  Pembelian;
  
  GRANT
  Create any table 
  to Pembelian;
  
GRANT UNLIMITED TABLESPACE TO Pembelian;
GRANT CONNECT, RESOURCE TO pembelian;
  
INSERT INTO barang (KODE_BARANG,NAMA_BARANG,SATUAN_BARANG,STOK_BARANG)
VALUES ('B001', 'Lemari Es', 'unit', 11);
Select * from barang;

INSERT INTO barang (KODE_BARANG,NAMA_BARANG,SATUAN_BARANG,STOK_BARANG)
VALUES ('B002', 'Rice Cooker', 'buah', 23);

INSERT INTO barang (KODE_BARANG,NAMA_BARANG)
VALUES('B003', 'TV');

INSERT INTO barang (KODE_BARANG,NAMA_BARANG,SATUAN_BARANG,STOK_BARANG)
VALUES ('B004', 'radio', 'buah', 21);

INSERT INTO SUPLIER(KODE_SUPLIER, NAMA_SUPLIER, ALAMAT_SUPLIER)
VALUES('s001', 'PT. Ani', 'Palembang');

INSERT INTO SUPLIER(KODE_SUPLIER, NAMA_SUPLIER, ALAMAT_SUPLIER)
VALUES('s002', 'PT. Budi', 'Lampung');

INSERT INTO SUPLIER(KODE_SUPLIER, NAMA_SUPLIER, ALAMAT_SUPLIER)
VALUES('s003', 'PT. Citra', 'Bandung');

SELECT * FROM SUPLIER;

DESCRIBE CUSTOMER;

INSERT INTO CUSTOMER(KODE_CUSTOMER, NAMA_CUSTOMER, ALAMAT_CUSTOMER)
VALUES ('c001', 'Doni', 'Baturaja');

INSERT INTO CUSTOMER(KODE_CUSTOMER, NAMA_CUSTOMER, ALAMAT_CUSTOMER)
VALUES ('c002', 'hana', 'palembang');

INSERT INTO CUSTOMER(KODE_CUSTOMER, NAMA_CUSTOMER, ALAMAT_CUSTOMER)
VALUES ('c003', 'lili', 'jakarta');

SELECT * FROM CUSTOMER;
SELECT * FROM BARANG;

UPDATE BARANG
SET (SATUAN_BARANG = 'unit',
 STOK_BARANG = 20)

