CREATE TABLE BARANG(
KODE_BARANG CHAR(6) NOT NULL PRIMARY KEY,
NAMA_BARANG VARCHAR(20),
SATUAN_BARANG VARCHAR(10))
;   

ALTER TABLE BARANG
ADD stok_barang INT;

CREATE TABLE SUPLIER(
KODE_SUPLIER CHAR(6) NOT NULL PRIMARY KEY,
NAMA_SUPLIER VARCHAR2(30),
ALAMAT_SUPLIER VARCHAR(50)
);

ALTER TABLE SUPLIER 
MODIFY ALAMAT_SUPLIER CHAR(40); 

CREATE TABLE CUSTOMER(
KODE_CUSTOMER CHAR(6)  NOT NULL PRIMARY KEY ,
NAMA_CUSTOMER VARCHAR2(30 ) NOT NULL,
ALAMAT_CUSTOMER VARCHAR(50) NOT NULL
);

CREATE TABLE PASOK(
KODE_PASOK CHAR(6) PRIMARY KEY NOT NULL,
JUMLAH_PASOK Int,
KODE_SUPLIER CHAR(6) NOT NULL,
KODE_CUSTOMER CHAR(6) NOT NULL
);

ALTER TABLE PASOK 
ADD CONSTRAINT FK_PASOK
foreign key (KODE_SUPLIER)
REFERENCES SUPLIER(KODE_SUPLIER) ON DELETE CASCADE;

ALTER TABLE PASOK 
ADD CONSTRAINT FK_CUSTOMER
FOREIGN KEY (KODE_CUSTOMER)
REFERENCES CUSTOMER(KODE_CUSTOMER)
;

CREATE TABLE PEMBELIAN(
KODE_PEMBELIAN CHAR(6) NOT NULL PRIMARY KEY ,
KODE_BARANG CHAR(6) NOT NULL,
KODE_CUSTOMER CHAR(6) NOT NULL,
CONSTRAINT FK_KODE_BARANG 
FOREIGN KEY (KODE_BARANG) 
REFERENCES BARANG(KODE_BARANG),
CONSTRAINT KEY_KODE_CUSTOMER
FOREIGN KEY (KODE_CUSTOMER)
REFERENCES CUSTOMER(KODE_CUSTOMER),
JUMLAH_PEMBELIAN INT
);

DESCRIBE BARANG;
DESCRIBE SUPLIER;
DESCRIBE CUSTOMER;
DESCRIBE PASOK;
DESCRIBE PEMBELIAN;

alter session set "_ORACLE_SCRIPT"=true;

disconnect;